V4Fire/Client

- package-lock.json
- package.json
- src/core/component/component.ts
- src/core/component/functional.ts
- src/core/component/index.ts
- src/core/component/vue.ts
- src/super/i-block/i-block.ts
- src/super/i-static-page/i-static-page.ts
* Removed `.event` from `@watch`
* Renamed `.$state`-> `.remoteState`
> Refactoring

- src/core/component/component.ts
- src/core/component/index.ts
- src/core/component/inherit.ts
- src/p-index/index.js
- src/p-index/p-index.ss
- src/super/i-block/i-block.ts
```
< b-remote-provider &
:watch = {
bla: [{field: '?global.document:mousemove', group: ':suspend'}]
}
.
```
> Watch prop

- src/super/i-block/i-block.ts
> New logging

- build/module.webpack.js
- build/replacers/project-name.js
- build/stylus/color.js
- build/stylus/size.js
- package-lock.json
- package.json
WIP
Refactoring color plugin
Rename GLOBAL in size plugin
Add @projectName replacer for stylus files
> Colors layer system refactoring

- src/base/b-link/b-link.ss
- src/base/b-list/b-list.ss
- src/base/b-window/b-window.ss
- src/core/component/index.ts
- src/form/b-button/b-button.ss
- src/form/b-checkbox/b-icon-checkbox/b-icon-checkbox.ss
- src/form/b-input/b-input.ss
- src/super/i-block/modules/vdom.ts
slot helper
getField -> field.get
> Slots improvements

- src/super/i-message/i-message.ts
remove the event when the i-message is reopened
> remove the event when the i-message is reopened

- src/base/b-slider/b-slider.ts
> Fix slider init without any properties

- src/base/b-image/b-image.ss
- src/base/b-image/b-image.styl
- src/base/b-image/b-image.ts
- src/pages/p-v4-components-demo/index.js
- src/pages/p-v4-components-demo/p-v4-components-demo.ss
More working cases are needed to test the behavior.
In the future, it is possible to implement the function of delayed loading of images.
> Reworked b-image component to be able to change aspect ratio.

- src/base/b-image/b-image.ts
> embed image if no ratio

- src/core/component/directives/in-view/modules/adapter.ts
- src/core/component/directives/in-view/modules/intersection/helpers.ts
- src/core/component/directives/in-view/modules/intersection/index.ts
- src/core/component/directives/in-view/modules/meta.ts
- src/core/component/directives/in-view/modules/mutation/index.ts
Странно работал delay на телефоне, вернул на timeout и delay теперь задается опционально
> fix/in-view: delay works not properly

- src/base/b-image/b-image.ss
- src/base/b-image/b-image.styl
Need to check on the bookalook
> bugfix collapse without pictures

- src/base/b-image/b-image.ts
> fix height calculation in some cases

- src/base/b-slider/b-slider.ts
This field must be not required by default
> Fast fix bslider

- CHANGELOG.md
- config/default.js
- index.d.ts
- src/base/b-virtual-scroll/b-virtual-scroll.ss
- src/base/b-virtual-scroll/b-virtual-scroll.ts
- src/base/b-virtual-scroll/modules/component-render.ts
- src/base/b-virtual-scroll/modules/helpers.ts
- src/base/b-virtual-scroll/modules/interface.ts
- src/base/b-virtual-scroll/modules/scroll-render.ts
- src/base/b-virtual-scroll/modules/scroll-request.ts
- src/core/component/directives/index.ts
- src/core/component/directives/resize/index.ts
- src/core/component/directives/resize/interface.ts
- src/core/component/directives/resize/resize.ts
- src/super/i-data/i-data.ts
- Улучшил производительность на ресайзах
- Пофиксил багу
> b-virtual-scroll improvements / bug fixes, add resize observer

- CHANGELOG.md
- src/base/b-image/b-image.ts
Set an image's height immediately after creating of component instead of after loading
> B-image fix

- src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
Fix parameter type in i-lock-page-scroll
> Fix parameter type

- src/super/i-block/modules/opt/index.ts
> Printing any changes as groups

- CHANGELOG.md
- src/base/b-virtual-scroll/b-virtual-scroll.ts
- src/super/i-block/CHANGELOG.md
- src/super/i-block/i-block.ts
- src/super/i-data/CHANGELOG.md
- src/super/i-data/i-data.ts
- Пофиксил баг с возможным вызовом `initLoad` дважды
- Добавил новое событие `initLoadStart`
> InitLoad fixes/improvmenets

- CHANGELOG.md
- package.json
- src/core/component/vnode/CHANGELOG.md
- src/core/component/vnode/index.ts
Когда стили заканчивются на ; то код падает
> Fixed parse empty rule

- build/test.gulp.js
- package.json
- src/core/dom/image/test/index.js
- tests/helpers/request.js
> Added retries for tests

- CHANGELOG.md
- src/core/component/render-function/CHANGELOG.md
- src/core/component/render-function/create-element.ts
> fix: fixed using `asyncRender` within nested flyweight components

- CHANGELOG.md
- build/stylus/CHANGELOG.md
- build/stylus/ds/CHANGELOG.md
- build/stylus/ds/index.js
- build/stylus/index.js
> Fixed subject

- CHANGELOG.md
- package-lock.json
- package.json
- src/form/b-input/CHANGELOG.md
- src/form/b-input/README.md
- src/form/b-input/b-input.ss
- src/form/b-input/b-input.styl
- src/form/b-input/b-input.ts
- src/form/b-input/test/runners/simple.js
* Add prop `additionalPhrase` to `b-input`
> Edadealcorecase 1350

- CHANGELOG.md
- package-lock.json
- package.json
- src/form/b-input/CHANGELOG.md
- src/form/b-input/README.md
- src/form/b-input/b-input.ts
- src/form/b-input/test/runners/simple.js
changed calculation of `textHintWithIndent` to concatenation `bInput.value` and `textHint` without space between it
> changed calculation of `textHintWithIndent`

- CHANGELOG.md
- src/base/b-router/CHANGELOG.md
- src/base/b-router/b-router.ts
- src/base/b-router/test/helpers/transition.js
Add `extendFilter` to `deepMixin` function in `emitTransition`
> Router fix

- CHANGELOG.md
- build/stylus/ds/plugins.js
- src/global/g-def/CHANGELOG.md
- src/global/g-def/funcs/ds.styl
> Added the ability to add shadows and gradients to the design system

- build/monic/attach-component-dependencies.js
- src/core/prelude/webpack.ts
Should be rebased and merged after the #914
> Optimize style load check

- package.json
- src/base/b-slider/CHANGELOG.md
- src/base/b-slider/README.md
- src/base/b-slider/b-slider.ts
- src/base/b-slider/const.ts
- src/base/b-slider/test/runners/gestures.js
- add new `alignLastToEnd` and `autoSlideInterval` props;
- fix `align="end"` behaviour
> Slider improvements

- src/components/directives/on-resize/test/unit/main.ts
- src/core/dom/resize-watcher/class.ts
- src/core/dom/resize-watcher/helpers.ts
- src/core/dom/resize-watcher/interface.ts
> #944 v-on resize tests and fix box behaviour

- src/components/traits/i-control-list/i-control-list.ts
Более понятный текст ошибки, так как action.method переехал в action.handler
> feat: action method -> action handler in TypeError message

- CHANGELOG.md
- package.json
- tests/config/super/index.ts
> V4.0.0.16 up version, fix CI value

- src/core/init/hydrated-route.ts
Get default route from compiled routes
> Fix hydrate-route init

- CHANGELOG.md
- package.json
- src/icons/b-icon/test/index.js
- src/traits/i-icon/CHANGELOG.md
- src/traits/i-icon/i-icon.ts
Изменение механизма обновления атрибута href элемента use в компоненте b-icon для устранения бага с открытием окна браузера при нажатии на svg-иконку, расположенную внутри ссылки.
> fix: fix i-icon trait (issues/1048)

- src/components/super/i-data/i-data.ts
- src/core/component/hydration/const.ts
- src/core/component/hydration/index.ts
Фикс ошибки, когда приходит 204 NO CONTENT в ответе от дата провайдера.
Сейчас в этом случае возникает ошибка гидрации
Пример компонента с ошибкой на скриншотах
> Fix no content api response hydration mismatch

- CHANGELOG.md
- build/snakeskin/CHANGELOG.md
- build/snakeskin/default-filters.js
- components-lock.json
- fat-html.components-lock.json
- src/core/component/init/CHANGELOG.md
- src/core/component/init/states/before-create.ts
- src/core/component/interface/CHANGELOG.md
- src/core/component/interface/component/component.ts
- src/core/component/interface/component/index.ts
- src/core/component/interface/component/test/b-component-interface-dummy/b-component-interface-dummy.ss
- src/core/component/interface/component/test/b-component-interface-dummy/b-component-interface-dummy.styl
- src/core/component/interface/component/test/b-component-interface-dummy/b-component-interface-dummy.ts
- src/core/component/interface/component/test/b-component-interface-dummy/index.js
- src/core/component/interface/component/test/helpers.ts
- src/core/component/interface/component/test/unit/main.ts
- src/core/component/render/wrappers.ts
This methods are used to define getRoot and getParent props for the component
> Refactor getRoot and getParent

- src/core/page-meta-data/class.ts
- src/core/page-meta-data/elements/title/engines/index.ts
- src/core/page-meta-data/elements/title/engines/ssr/index.ts
- src/core/page-meta-data/store/index.ts
Fixed store iteration, added SSR engine for the Title element.
> Fix pageMetaData

- package.json
- yarn.lock
https://github.com/terser/terser/issues/1432
> chore(deps): update terser to 5.31.0

- src/components/base/b-dynamic-page/CHANGELOG.md
- src/components/base/b-dynamic-page/b-dynamic-page.ts
Фиксит вот эту историю: https://github.com/V4Fire/Client/issues/1325
> Activate component on hydration complete

- .github/workflows/release.yml
> Add workflow to deploy to NPM on release

- CHANGELOG.md
- src/components/base/b-virtual-scroll-new/modules/factory/index.ts
- src/components/dummies/b-dummy/b-dummy.ts
- src/core/prelude/test-env/components/index.ts
- b-dummy
- b-virtual-scroll-new
- globalThis.renderComponents
> chore: fix normalization of the forceUpdate props declared as `*Prop`

- build/webpack/module/rules/ss.js
> fix(build): fix exports name for snakeskin

- package.json
- src/core/std.ts
- yarn.lock
It is required for core/dom/resize-watcher
> feat: add resize-observer-polyfill

- CHANGELOG.md
- src/components/super/i-block/CHANGELOG.md
- src/components/super/i-block/i-block.ss
- src/components/super/i-block/i-block.ts
- src/core/component/meta/CHANGELOG.md
- src/core/component/meta/create.ts
> Remove excess spaces from the component's HTML output

- src/core/prelude/test-env/gestures.ts
> fix gestures Bonkalol/changed touches
