V4Fire/Client

- webpack.config.js
Я не учёл того что следовало бы исключить workers из первого лоадера, и неправильно интерпретировал значение флага helpers [(пруф)](https://babeljs.io/docs/plugins/transform-runtime/#optionshelpers)
> fix mistake

- src/core/component/decorators/base.ts
- src/core/component/inherit.ts
- src/p-index/p-index.ts
```js
@component()
class iBla extends iBlock {
get foo(): number {
return 1;
}
}
@component()
class iFoo extends iBla {
@field()
foo: number = 42;
created(): void {
console.log(this.foo); // 42
}
}
```
```js
@component()
class iBla extends iBlock {
@field()
foo: number = 1;
}
@component()
class iFoo extends iBla {
get foo(): number {
return 42;
}
created(): void {
console.log(this.foo); // 42
}
}
```
> Accessors overriding

- src/super/i-static-page/i-static-page.interface.ss
in chrome it's work only from 68 and higher versions
check browser support:
http://kangax.github.io/compat-table/es2016plus/ - Optional catch binding
> Fix catch {} in chrome 

- src/base/b-window/b-window.styl
Set `z-index` of `b-window` the same as `z-index` of `b-dialog`. So now it's higher than `z-index` of `b-cats-list`
> Changed z-index of b-window to 'overall'

- src/base/b-list/b-list.ss
It is possible now to display multiple lists instead of one in the components that inherit b-list, with data distributed among them.
List of changes:
1. `list` block of `b-list` remplate is remade to be functional with value option, it is now moved to `headHelpers` block of `index` template;
2. `id` parameter of `getElClasses` linking function now obtains `values[el.value]` as a value, so that all the lists get items with integral ids to distinguish them
> Added possibility to display multiple lists instead of one

- src/core/data/index.ts
- src/super/i-data/i-data.ts
Рассказывал давно тебе про эту проблему, в общем как неймспейс для провайдеров использовалось имя класса, что создавало коллизию Campaigns КБ и Campaigns купонов например
> Fix providers namespace collisions

- src/base/b-image/b-image.styl
Сейчас если в слот `broken` одного `b-image` вставить другой `b-image`, то стили верхнего будут влиять на внутренний:
```
< b-image :src = url1
< template #broken
< b-image :src = url2
```
> Fix b image

- src/base/b-router/b-router.ts
While b-router setting a page that exists in routes, the component doesn't take in account alias and redirect fields
> Correctly process alias and redirect fields

- CHANGELOG.md
- src/traits/i-access/i-access.styl
Из-за стиля `pointer-events: none` на задизейбленной кнопке не происходит события `onClick` и, соответственно, не вызывается его обработчик, который должен останавливать всплытие события.
В итоге, если задизейбленная кнопка с `position: fixed` находится поверх какого-то другого элемента, с которым может взаимодействовать пользователь, то при нажатии на эту кнопку пользователь на самом деле нажмёт находящийся под кнопкой элемент.
> Fix i-access

- CHANGELOG.md
- src/base/b-virtual-scroll/b-virtual-scroll.ts
- src/base/b-virtual-scroll/modules/scroll-render.ts
**Проблема**
При частом изменении пропа `request` и медленном интернете отображаются неверные данные.
**Причина**
* При изменении пропа `request` вызывается `reInit` в `scroll-render`'е, который вешает обработчик на событие `localReady`, выполняющийся один раз.
* После этого абортится предыдущий запрос `b-virtual-scroll`'а, который обрабатывается в методе `onRequestError`, эмитящем событие `localReady` и делается новый запрос.
* Это событие перехватывает `scroll-render` и выполняет метод `onReady`, отрисовывая старые данные (`options`) последнего успешного запроса `b-virtual-scroll`'а.
* Когда приходит ответ на новый запрос, он никем не обрабатывается, т.к. обработчик внутри `scroll-render`'а уже один раз выполнился.
**Решение**
Разделение событий на успешное получение и обработку данных …
> B virtual scroll on error fix

- src/base/b-virtual-scroll/modules/scroll-render.ts
The field `ScrollRender.chunk` in functions `ScrollRender.onReady` and `ScrollRender.render` is used as _next chunk that will be rendering when is needed_. But the function `ScrollRender.onNodeIntersect` use it as _"last rendered chunk"_. Provided PR fix this inconsistency.
> Fix rendering next chunk in b-virtual-scroll

- src/base/b-image/b-image.ts
It's not possible to get `naturalHeight` or `naturalWidth` before image loaded. Default image ratio always was 1 but now it will be updated after loading an image.
> Fixed the bug with default image ratio in b-image

- package.json
- src/base/b-list/b-list.ts
- src/form/b-button/b-button.ts
- src/form/b-calendar/b-calendar.ts
- src/form/b-input/b-input.ts
- src/global/g-icon/g-icon.interface.styl
- src/global/g-icon/g-icon.styl
- src/global/g-icon/index.js
- src/icons/b-progress-icon/b-progress-icon.ts
- src/traits/i-icon/modules/icons.ts
- Stop adding attribute `fill="currentColor"` to all elements of SVG sprites
- Remove unused getIconLink methods
With this change any svg can be used as sprite, not only one-colored ones.
What's more, colors of two-colored SVGs can be controlled with CSS or attributes at the root:
```svg
<svg viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg" fill="red" color="blue">
<rect x="2" y="2" width="50" height="50" stroke="currentColor" stroke-width="4"/>
</svg>
```
**WARNING!** This PR leads to breaking change: all `fill` attributes must be removed from SVG sprites.
> Improve SVG sprites

- src/base/b-bottom-slide/CHANGELOG.md
- src/base/b-bottom-slide/b-bottom-slide.ts
В `b-bottom-slide` в методе `initGeometry` нужно удалить проставление `paddingBottom`, т.к. высота `currentPage` на этот момент уже высчитана и проставляется всему контенту шторки через `content.style.height`. Добавление же паддинга приводит к уменьшению доступной высоты для контента и появлению полосы прокрутки
Правильнее выставлять паддинг через стили
> Удаление padding-bottom

- CHANGELOG.md
- build/module.webpack.js
- build/static.gulp.js
- Исправление генерации webp-изображений
- Исправление подключения webp-изображений в проект
`image-webpack-loader` не умеет создавать _копии_ webp-изображений. При этом он конвертирует существующие png/jpeg в webp, не изменяя при этом их расширений.
Некоторые issues:
- https://github.com/tcoopman/image-webpack-loader/issues/179#issuecomment-460757281
- https://github.com/tcoopman/image-webpack-loader/issues/138#issuecomment-497456326
> [Build] Fix webp images generating and loading

- CHANGELOG.md
- src/base/b-bottom-slide/CHANGELOG.md
- src/base/b-bottom-slide/b-bottom-slide.ts
- Для элемента страницы выставлять `maxHeight` без учета шапки шторки. Раньше максимальная высота для страницы включала в себя высоту шапки, хотя на самом деле шапка находится вне страницы;
- Общую высоту контента (включая шапку) проставлять для элемента `window`, т.к. он содержит в себе уже и шапку, и страницу.
> [bBottomSlide] Исправление отображения высокого контента

- src/core/component/engines/vue/vnode.ts
- src/core/component/flyweight/index.ts
Directive `v-image` **and any other directive** cannot be applied at root node in functional and composite components. Directive can be added to root node this way:
```
- namespace [%fileName%]
- include 'super/i-block'|b as placeholder
- template index() extends ['i-block'].index
- rootWrapper = true
- block rootAttrs
? Object.assign(rootAttrs, {'v-image': '{src: imageUrl}'})
```
But it doesn't work due to the bug caused by mistake in patching virtual nodes. The PR fixes this misbehaviour.
> Fix directives in functional and composite components

- CHANGELOG.md
- src/core/dom/image/CHANGELOG.md
- src/core/dom/image/loader.ts
`v-image` directive unbinding leads to clearing an element's state. So it calls method `setBackgroundImage` of `ImageLoader` and passes empty string as an `imageSrc` param. In this case the element's `backgroundImage` becomes url of empty string, i.e. `url('')`.
The PR fixes this behaviour.
> v-image fix

- CHANGELOG.md
- build/CHANGELOG.md
- build/gulp/test.js
Сабж: билд компонентых тестов выполнялся параллельно запуску тестов, почему тесты работают - сказать сложно )
Этот PR делает build опять нормально работающим
[Раньше Finished 'test:component:build' after 1.25 min](https://github.com/V4Fire/Client/runs/4310678389?
check_suite_focus=true)
[Cейчас Finished 'test:component:build' after 182 ms](https://github.com/V4Fire/Client/runs/4921099033?check_suite_focus=true)
> Fixed an issue with test command did not wait for build operation

- src/components/base/b-bottom-slide/b-bottom-slide.ts
> fix(b-bottom-slide): add getFullElementName to proto

- src/components/base/b-bottom-slide/b-bottom-slide.ts
This hook is not needed anymore as we are now using Vue teleport.
> fix(b-bottom-slide): remove beforeDestroy hook

- CHANGELOG.md
- build/helpers/CHANGELOG.md
- build/helpers/webpack.js
- build/webpack/CHANGELOG.md
- build/webpack/plugins/ignore-invalid-warnings.js
- build/webpack/snapshot.js
- build/webpack/watch-options.js
- config/CHANGELOG.md
- config/default.js
Этот PR добавляет env переменную `managed-libs`, которая позволяет указать дополнительные библиотеки (помимо слоев) для исключения из кэша и ватчинга.
Также был настроен `snapshot.managedPaths`, который исключает из кэша слои, но при этом кэширует остальные зависимости из node_modules.
> Setup webpack managed paths

- src/traits/i-lock-page-scroll/CHANGELOG.md
- src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
Из за того что возвращаемый lock методом промис обернут с параметром join: true, а requestAnimationFrame вызывается без этого параметра, то повторный вызов lock, до того как сработает коллбек requestAnimationFrame, уничтожит старый поток requestAnimationFrame, но из-за join: true метод lock вернет старый промис, который никогда не зарезолвится, тк вызов коллбека resolve происходил в коллбеке прошлого requestAnimationFrame
> Фикс бага метода lock трейта iLockPageScroll

- build/snakeskin/filters/tag-name.js
Always create an element with v-tag directive
to be consistent with rootTag prop
> chore(tag-name): fix rootTag behavior in snakeskin

- src/components/base/b-sidebar/b-sidebar.ts
- src/components/base/b-tree/b-tree.ts
- src/components/form/b-select/b-select.ts
При разработке приложения обнаружил, что есть ошибка при вызове метода `dom.delegateElement` в `b-tree`. При этом юнит-тесты в клиенте выполняются без ошибок: видимо это связано с тем, что в бандл попадает нужный метод через какой-то другой компонент.
Наши юнит-тесты не совсем надежны.
> Add missing methods to friend classes (block, dom) prototypes

- src/core/dom/intersection-watcher/test/unit/options.ts
- src/core/dom/intersection-watcher/test/unit/root.ts
- src/core/dom/intersection-watcher/test/unit/unwatch.ts
- src/core/dom/intersection-watcher/test/unit/watch.ts
Добавлены тест-кейсы, покрывающие случаи, описанные в issue #1017 (одновременное наблюдение нескольких элементов, расположенных на странице определённым образом).
Скорректирован порядок запуска тест-кейсов с заданным root-элементом, увеличены временные задержки после скроллинга (предотвращение race conditions).
> Intersection-watcher unit test updates (Issues/1017)

- src/components/base/b-router/test/helpers.ts
- src/components/base/b-router/test/unit/links-on-page.ts
- src/components/base/b-router/test/unit/scroll-control.ts
- src/components/base/b-router/test/unit/simple.ts
- src/components/base/b-router/test/unit/transition/events.ts
- src/components/base/b-router/test/unit/transition/parameters.ts
- src/components/base/b-router/test/unit/transition/routes.ts
- src/components/base/b-router/test/unit/watch.ts
Глобальная настройка маршрутов удалена из helper'а createInitRouter, настройка роутера теперь осуществляется непосредственно перед тестами.
Поправлены некоторые тест-кейсы (более явная работа с маршрутами).
Внесены стилевые изменения.
> b-router unit tests refactoring (Issues/966)

- src/components/super/i-page/README.md
- src/components/super/i-page/i-page.ts
- src/components/super/i-page/interface.ts
Обновлён тип `DescriptionValue` для пропа `pageDescriptionProp`, т.к. он тоже может быть задан функцией (соответствующий sync.link это предполагает).
Внесены исправления/дополнения в документацию.
В методе `scrollTo` тернарники заменены на ?? (замечание линтера).
> Fix i-page interface and documentation

- CHANGELOG.md
- src/components/form/b-select/CHANGELOG.md
- src/components/form/b-select/b-select.ss
- src/components/form/b-textarea/CHANGELOG.md
- src/components/form/b-textarea/b-textarea.ss
- src/components/super/i-block/CHANGELOG.md
- src/components/super/i-block/i-block.ss
- src/components/super/i-input/CHANGELOG.md
- src/components/super/i-input/i-input.ss
- src/components/super/i-static-page/i-static-page.component.ss
- src/components/super/i-static-page/i-static-page.html.ss
В https://github.com/V4Fire/Client/pull/1002 случился Breaking Change, который привел к тому, что верстка, заданная в `helpers` переехала на место перед основным телом компонента. Поэтому делаем новые специальные блоки, которые позволят задавать верстку до и после основного тела компонента
> feat(template): add additional blocks for footer and header of component

- src/components/friends/block/class.ts
During component destruction this property could not be deleted, which could cause memory leaks
> fix(components/friends/block): make `$el` configurable

- CHANGELOG.md
- src/components/super/i-block/CHANGELOG.md
- src/components/super/i-block/i-block.ss
Wait функция для SSR имеет вид: `() => { const {Promise} = global; return new Promise(() => {}); }`, далее она интепорлируется в шаблон и вызывается через `${filter}?.()`, чтобы корректно обрабатывать таким образом заданные функции завернул `${filter}`  в скобки
> Add parentheses for the wait function in loadModules

- CHANGELOG.md
- src/components/form/b-select/CHANGELOG.md
- src/components/form/b-select/b-select.ts
Заметил при разработке такую ошибку, в тестах всё ок, полагаю как-то иначе в бандл попадают эти методы в тестах
> fix(b-select): add missing methods to Block prototype

- CHANGELOG.md
- src/components/form/b-select/CHANGELOG.md
- src/components/form/b-select/b-select.ts
- src/components/form/b-select/test/unit/simple.ts
- src/components/friends/dom/CHANGELOG.md
- src/components/friends/dom/component.ts
- src/components/friends/dom/test/unit/main.ts
- src/components/traits/i-open/i-open.ts
Столкнулся с проблемой, что дропдаун селекта не закрывается при клике на элемент с `.stopPropagation` и так же при клике на любой компонент с инстансом `iBlock`, мне кажется в таких кейсах закрытие дропдауна ожидаемое поведение.
https://github.com/V4Fire/Client/assets/51162910/f763931b-5ba9-4443-8e28-6a073d2d5254
https://github.com/V4Fire/Client/assets/51162910/5fc53415-54b8-4827-b9ef-48ef5e0d7077
> fix(b-select): close dropdown on click outside

- src/components/directives/image/CHANGELOG.md
- src/components/directives/image/index.ts
- src/components/directives/image/interface.ts
**Проблема:** 
Сейчас при успешной загрузке изображения добавляется таймаут в 50 мс, прежде, чем preview-изображение будет заменено на загруженное изображение.
Андрей не вспомнил зачем это было сделано, но я предполагаю, что смысл в том, чтобы не было моментального мигания заглушки, когда изображение загружается достаточно быстро.
Но это обернулось так, что теперь эти 50 мс добавляются даже для изображений, загруженных из кэша браузера. Выглядит так, что на главной едадила листаем слайдер, изображения подгружаются, но если листать обратно, выглядит будто предыдущие изображения загружаются повторно.
**Решение:**
Собственно, моё решение — убрать таймаут для изображений, которые браузер уже загрузил ранее. Если изображение еще не загружалось, то `onLoad` сработает, когда изображение будет …
> Fix v-image to work correctly with cached images

- build/monic/attach-component-dependencies.js
Try load styles even if template already loaded. This fix style load on templates loaded via another template without styles.
> fix don't skip style load on loaded template

- CHANGELOG.md
- src/components/base/b-virtual-scroll/b-virtual-scroll.ts
Убираем поддержку API с остаточными параметрами в `addToPrototype`, см https://github.com/V4Fire/Core/pull/388
Больше нигде не используется в v4fire/client такой api, только в b-virtual-scroll
> refactor: `addToPrototype` using

- CHANGELOG.md
- src/core/component/render/CHANGELOG.md
- src/core/component/render/wrappers.ts
Добавлены возможные типы для source в методе renderList и исключено падение если на входе undefined/null
В оригинале есть function `renderList<T>(source: T, ...`
> fix crash on undefined/null source

- CHANGELOG.md
- package.json
- src/dummies/b-dummy/CHANGELOG.md
- src/dummies/b-dummy/b-dummy.ts
In dummy override baseMods there was no call of super. It's affects on extended components from bDummy
> fix: add super call in baseMods override

- CHANGELOG.md
- src/components/form/b-button/b-button.ts
- src/components/super/i-input/CHANGELOG.md
- src/components/super/i-input/i-input.ts
- src/components/traits/i-progress/CHANGELOG.md
- src/components/traits/i-progress/README.md
- src/components/traits/i-progress/i-progress.ts
Убрал установку `disabled` для компнента на время валидации, и убран фикс востанавливающий фокус на копоненте после `disabled`.
Установка `disabled` приводила к потери фокуса и последующим дерганиям экранной клавиатуры и глюкам саджестов самой клавиатуры на устройствах с Android 12 и ниже.
При попытке спрятать экранную клавиатуру (жестом или кнопкой назад) запускалась валидация с циклом потери/установи фокуса, что приводило к повторному появлению клавиатуры.
Считаю `disabled` в процессе валидации (фактически на каждое нажатие клавиш) на поле ввода может приводить так же к потере вводимых пользователем символов, потере позиции курсора и прочим нежелательным спецэффектам.
Fixes #1203
> [issue/1203] Fix hide on-screen keyboard when there are validators on the input field

- CHANGELOG.md
- components-lock.json
- fat-html.components-lock.json
- src/components/base/b-bottom-slide/CHANGELOG.md
- src/components/base/b-bottom-slide/README.md
- src/components/base/b-bottom-slide/b-bottom-slide.ss
- src/components/base/b-bottom-slide/b-bottom-slide.ts
- src/components/base/b-bottom-slide/index.js
- src/components/base/b-bottom-slide/test/unit/main.ts
Use a directive instead watchers to catch changes that do not affect DOM (for example uploading an image)
> refactor: use the `v-on-resize` directive to recalculate `b-bottom-slide` state

- CHANGELOG.md
- components-lock.json
- fat-html.components-lock.json
- package.json
- src/base/b-bottom-slide/CHANGELOG.md
- src/base/b-bottom-slide/README.md
- src/base/b-bottom-slide/b-bottom-slide.ss
- src/base/b-bottom-slide/b-bottom-slide.ts
- src/base/b-bottom-slide/index.js
Use a directive instead watchers to catch changes that do not affect DOM (for example uploading an image)
> refactor: use the `v-resize-observer` directive to recalculate `b-bottom-slide` state

- src/components/super/i-static-page/i-static-page.html.ss
Не рендерить заголовок страницы в html-шаблоне при гидратации. Этим избегаем дублирования элемента `title` на странице, так как мета-информация из `pageMetaData` встраивается в шаблон на bff-сервере.
> fix: add conditional render of the page title

- CHANGELOG.md
- src/components/super/i-block/test/unit/destructor.ts
- src/core/component/engines/directive.ts
- src/core/component/engines/vue3/component.ts
- src/core/component/functional/helpers.ts
- src/core/component/functional/test/b-functional-button-dummy/b-functional-button-dummy.ss
- src/core/component/functional/test/b-functional-button-dummy/b-functional-button-dummy.ts
- src/core/component/functional/test/b-functional-dummy/b-functional-dummy.ts
- src/core/component/functional/test/unit/main.ts
- src/core/component/init/states/before-create.ts
- src/core/component/init/states/before-destroy.ts
- src/core/component/init/states/created.ts
- src/core/component/interface/CHANGELOG.md
- src/core/component/interface/component/component.ts
- src/core/component/interface/component/types.ts
Enable control over both the recursion of the destructor and the execution of unmount handlers in the directives used within the component
> fix(core/component/interface): enhance destructor options

- CHANGELOG.md
- components-lock.json
- package.json
- src/core/component/accessor/CHANGELOG.md
- src/core/component/accessor/index.ts
- src/core/component/functional/helpers.ts
- src/core/component/functional/index.ts
- src/core/component/functional/test/b-functional-button-dummy/b-functional-button-dummy.ss
- src/core/component/functional/test/b-functional-dummy/b-functional-dummy.ss
- src/core/component/functional/test/b-functional-dummy/b-functional-dummy.ts
- src/core/component/functional/test/b-functional-getters-dummy/b-functional-getters-dummy.ss
- src/core/component/functional/test/b-functional-getters-dummy/b-functional-getters-dummy.styl
- src/core/component/functional/test/b-functional-getters-dummy/b-functional-getters-dummy.ts
- src/core/component/functional/test/b-functional-getters-dummy/const.ts
- src/core/component/functional/test/b-functional-getters-dummy/index.js
- src/core/component/functional/test/b-functional-getters-dummy/interface.ts
- src/core/component/functional/test/unit/getters.ts
- src/core/component/functional/test/unit/main.ts
- yarn.lock
Ключевое изменение в src/core/component/accessor/index.ts.
Теперь для функциональных компонентов значения computed getter'ов не сохраняются в кэш во время рендера.
> fix: reset cache after restore

- CHANGELOG.md
- components-lock.json
- src/core/component/render/CHANGELOG.md
- src/core/component/render/helpers/attrs.ts
- src/core/component/render/helpers/flags.ts
- src/core/component/render/helpers/index.ts
- src/core/component/render/helpers/test/b-component-render-flags-dummy/b-component-render-flags-dummy.ss
- src/core/component/render/helpers/test/b-component-render-flags-dummy/b-component-render-flags-dummy.styl
- src/core/component/render/helpers/test/b-component-render-flags-dummy/b-component-render-flags-dummy.ts
- src/core/component/render/helpers/test/b-component-render-flags-dummy/index.js
- src/core/component/render/helpers/test/unit/flags.ts
- src/core/component/render/wrappers.ts
If a vnode has special attributes, its patch flag must be modified before the original vnode creation function is called. This ensures that Vue will correctly initialize the vnode
> fix(core/component/render): modify vnode patch flags before its creation

- CHANGELOG.md
- src/components/super/i-block/CHANGELOG.md
- src/components/super/i-block/i-block.ss
Добавление блока-обёртки для контента. Продиктовано необходимостью возможности отрисовать элемент/компонент при SSR в случае, когда рендеринг основного содержимого запрещён через проп `ssrRendering`. Ранее в отдельный блок были выделены скелетоны, но рациональнее иметь общую обёртку на такой случай.
> Add a `rootContent` wrapper block

- CHANGELOG.md
- package.json
- src/components/base/b-router/CHANGELOG.md
- src/components/base/b-router/modules/transition/class.ts
В этом [коммите](https://github.com/V4Fire/Client/commit/91565b0b03b9dcf8ed31cc7984cba4bfb5c9a4d3#diff-a893b891296f4b543669b02282d884c013e14e9603aec82ee1b831ea0a7d5d25L160) добавилось оборачивание метода обновления скролла страницы в `async.promise`, из-за чего стала стрелять ошибка при создании самого первого перехода на страницу в [этом месте](https://github.com/V4Fire/Client/blob/v4/src/components/base/b-router/modules/transition/class.ts#L271)
Добавил в параметры для `async.promise` `join: 'replace'`
> fix(b-router/modules/transition): fix promises collision

- CHANGELOG.md
- package.json
- src/super/i-static-page/CHANGELOG.md
- src/super/i-static-page/README.md
- src/super/i-static-page/modules/ss-helpers/libs.js
`addPublicPath` внутри проверяет на `webpack.dynamicPublicPath()`. Если последнее `true`, то возвращается js-код с PUBLIC_PATH в качестве link href даже для внешних ссылок, что не есть ожидаемое поведение
> fix: add p.source external check

- CHANGELOG.md
- package.json
- src/super/i-static-page/CHANGELOG.md
- src/super/i-static-page/modules/ss-helpers/libs.js
Fixed an implicitly infinite loop when we tried to wait for external (that means it is externally-hosted) library to appear in filesystem
> fix: do not wait for external library to appear in filesystem

- CHANGELOG.md
- src/components/super/i-block/CHANGELOG.md
- src/components/super/i-block/modules/listeners/index.ts
- src/components/super/i-block/test/unit/listeners.ts
It fixes the bug when the listener might be called after the component has been destroyed
> fix(i-block): apply async.proxy for the global event listeners

- CHANGELOG.md
- src/components/super/i-data/CHANGELOG.md
- src/components/super/i-data/i-data.ts
- src/components/super/i-data/test/unit/main.ts
- tests/CHANGELOG.md
- tests/helpers/mock/README.md
- tests/helpers/mock/index.ts
- tests/helpers/mock/interface.ts
> fix(i-data): `componentStatus` updating after component destroying

- CHANGELOG.md
- src/core/component/decorators/CHANGELOG.md
- src/core/component/decorators/component/index.ts
> fix(core/component/decorators): override component name in meta

- CHANGELOG.md
- src/core/shims/index.ts
Сейчас всегда используется полифилл для requestIdleCallback из core/shims/ssr. Этот PR исправляет это и использует полифилл из assets/lib/requestidlecallback.js
> fix(core/shims): import ssr shims only in SSR

- CHANGELOG.md
- src/core/shims/index.ts
It seems that SSR version of requestIdleCallback polyfill is better
> chore: revert exclude ssr shims

- CHANGELOG.md
- src/core/component/directives/render/CHANGELOG.md
- src/core/component/directives/render/index.ts
- src/core/component/directives/render/interface.ts
- src/core/component/engines/CHANGELOG.md
- src/core/component/engines/interface.ts
При серверном рендере учитывалось, что в массиве могут присутствовать асинхронные чанки, но не учитывалось, что могут быть вложенные массивы строк.
Вот тут указано, что в буфере могут быть строки, асинхронные буферы и рекурсивные массивы строк: https://github.com/vuejs/core/blob/main/packages/server-renderer/src/render.ts#L61-L65
> Исправление рендера вложенных чанков в SSR

- CHANGELOG.md
- src/core/page-meta-data/CHANGELOG.md
- src/core/page-meta-data/elements/abstract/engines/dom/index.ts
Бывает, что в title/description прилетает строка с кавычками, например `Игрушка "Воздушный змей", Sport&Fun, в ассортименте – купить по выгодной цене в Москва – Едадил`. Вставляется в DOM нормально, но при создании селектора `meta[title="Игрушка "Воздушный змей", Sport&Fun, в ассортименте – купить по выгодной цене в Москва – Едадил"]` будет ошибка.
> fix(page-meta-data): handle quotation marks in query selector

- CHANGELOG.md
- src/components/super/i-block/modules/activation/CHANGELOG.md
- src/components/super/i-block/modules/activation/index.ts
- src/components/super/i-block/modules/activation/test/unit/reload.ts
- src/components/super/i-data/i-data.ts
Мы перед созданием компонента вызываем `initLoad`, до его завершения мы покидаем страницу, если ещё точнее, нас волнует поле `isReadyOnce`, оно остается `false`. Затем возвращаемся на эту страницу, мы попадаем в `onActivated` и регистрируем `setImmediate` https://github.com/V4Fire/Client/blob/503435cdc7e12edf2236a63dc01253c4115f909d/src/components/super/i-block/modules/activation/index.ts#L185
после этого продолжается запрос `initLoad` и выставляется `isReadyOnce = true`. После чего вызывается колбэк из `setImmediate`, который в зависимости от `isReadyOnce` вызывает либо `reload`, либо `initLoad`
https://github.com/V4Fire/Client/blob/503435cdc7e12edf2236a63dc01253c4115f909d/src/components/super/i-block/modules/activation/index.ts#L199-L201
В `reload` у нас в `i-data` есть `(await …
> fix(i-block/activation): reload for unloaded component or with `reloadOnActivation`

- CHANGELOG.md
- build/snakeskin/CHANGELOG.md
- build/snakeskin/filters/tag.js
- components-lock.json
- src/components/pages/p-v4-components-demo/index.js
- src/components/pages/p-v4-components-demo/p-v4-components-demo.ss
- src/core/component/directives/ref/index.ts
- src/core/component/directives/ref/test/b-directives-ref-dummy/b-directives-ref-dummy.ss
- src/core/component/directives/ref/test/unit/main.ts
- src/core/component/engines/vue3/render.ts
- src/core/component/render/CHANGELOG.md
- src/core/component/render/wrappers.ts
Дебажил на следующем примере:
```js
< . v-async-target
+= self.render({ wait: 'async.sleep.bind(async, 0)' })
< b-dummy ref = rfc
< b-dummy ref = nested | v-func = false
```
Проблема в том, что при наличии v-func v-ref не преобразовывается в проп, а остается директивой.
Когда v-ref является пропом и асинхронно рендерится слот, то у нас явно в качестве this пробрасывается контекст в котором этот слот объявлен:
Далее в resolveAttrs этот this пробрасывается как instance в директиву, тем самым верно определяется цель для записи рефов:
https://github.com/V4Fire/Client/blob/a779b615409516ba46b69a891bf7e7c495b352a1/src/core/component/render/helpers/attrs.ts#L107-L124
**UPD:** оказывается instance в обоих случаях верный, но в случае вызова resolveAttrs и invokeDirectiveHook vnode имеет разные …
> Fix ref tests

- CHANGELOG.md
- src/core/component/watch/CHANGELOG.md
- src/core/component/watch/bind.ts
After rewriting the loop from `.forEach` to native `for`, `return` statement was not changed to `continue`.
> fix(core/component/watch): binding non-promise handler for custom watcher
